name: K8S Github Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        # 安装 Docker
        curl -fsSL https://get.docker.com/ -o get-docker.sh && sh get-docker.sh
        docker info
        # 初始化一个k3s的master节点
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh - --docker
        # 完善配置
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        # 检查集群运行情况
        kubectl get nodes
        # 查看已创建容器
        kubectl get pods --all-namespaces
    - name: example tests
      run: |
        kubectl cluster-info
        kubectl create deployment --image nginx my-nginx
        kubectl get po
