name: K8S Github Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        # 检查 Docker
        docker info
        # 安装k3s
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh - 
        # 完善配置
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
    - name: node check
      run: |
        # 检查服务状态
        kubectl get serviceaccount default -n default
        # 检查集群运行情况
        echo “集群运行情况：”
        kubectl get nodes
    - name: pod test
      run: |
        # 创建一个容器
        kubectl run first-container --image=docker.io/library/nginx --port=80
        # 查看已创建容器状态
        kubectl get pods
        # 使用docker命令查看容器状态
        docker ps
