name: K8S Github Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    # 检出仓库代码
    - uses: actions/checkout@v2
    - name: install k8s
      run: |
        # 安装k3s
        curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh - 
        # 完善配置
        cat /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

    - name: default account create
      run: |
        # 创建默认服务账号
        kubectl create serviceaccount default -n default
        # 检查服务状态
        kubectl get serviceaccount default -n default

    - name: node check
      run: |
        # 检查集群运行情况
        sleep 2
        echo 集群运行情况：
        kubectl get nodes

    # - name: pod test
    #   run: |
    #     # 创建一个包含nginx容器的pod
    #     kubectl run first-container --image=docker.io/library/nginx --port=80
    #     # 查看已创建pod状态
    #     sleep 15
    #     echo pod状态:
    #     kubectl get pods

    # - name: container test
    #   run: |
    #     sleep 5
    #     # 查看 Pod 详情
    #     # echo pod describe:
    #     # kubectl describe pod first-container
    #     echo first-container -o wide
    #     kubectl get pods first-container -o wide

    #     # 尝试访问Nginx Container
    #     curl 10.42.0.3:80

    - name: deployment test 
      run: |
        # 尝试创建3个副本的Deployment
        kubectl apply -f ./k3s/deployment.yaml
        # 查看Deployment状态
        sleep 15
        echo deployemt 状态：
        kubectl get deployment
        echo pod状态:
        kubectl get pods
    
    - name: service test
      run: |
        # 尝试在此前Deployment基础上建立Service
        kubectl apply -f ./k3s/service.yaml
        # 查看Service状态
        sleep 25
        echo service 状态：
        kubectl get svc
        echo pod状态:
        kubectl get pods

        # 用脚本获取cluster-ip并尝试访问Service
        chmod +x ./k3s/catch_clusterip.sh
        ./k3s/catch_clusterip.sh
